### ISSUE TITLE
Error when installing patch

### ISSUE THREAD

**Issue by SimoneFromThePlantLab** [Drmirdeep/drmirdeep.github.io#5]
Hello,

I'm trying to install miRDeep2, and everything goes fine till the point where I have to install the patch; the terminal gives me bacj the error:
"miRDeep2 seems not to be in your global PATH variable
please use the install.pl script first or add it manutally to your PATH variable before applying the patch"

What should I do?

Thanks!

Simone

**Comment by mschilli87** [comment]
@SimoneFromThePlantLab:
> What should I do?

To answer this, we'd need to know what you *did* already.

> I'm trying to install miRDeep2
How?

> everything goes fine
What is 'everything'?
How do you know it is going fine?

> where I have to install the patch
Which patch?
Why do you need to install it?

> the terminal gives me [...] the error: "miRDeep2 seems not to be in your global PATH variable please use the install.pl script first or add it manutally to your PATH variable before applying the patch"
And? Did you do what was suggested in the error message?
What happened?

Please provide us with the information what system you are on, where you got miRDeep2 from, which version you are trying to install, how you did so and what was the result. The last to points should include the exact commands you run in the Terminal and the corresponding output, both as copy/paste-able (Markdown-formatted) text, not as screenshots we'd have to manually type from to reproduce your problem.

--
*edit*: I forgot: Most importantly, please provide that information in a new issue on the [miRDeep2 repository](https://github.com/rajewsky-lab/mirdeep2) after you close this one, since this is the issue tracker for [a webpage](https://drmirdeep.github.io/). :wink:

**Comment by SimoneFromThePlantLab** [comment]
Hello, 

thank you for your answer. I solved the probelm by simply replacing the files from the patch folder to the miRDeep2 one.

Thanks again!

**Comment by Drmirdeep** [comment]
The patch files are from 2017. We had several releases in between so I would not use them anymore.
